version: '3.5'
name: catalog

services:
  catalogDb:
    container_name: ps_catalogdb
    image: mongo
    restart: always
    volumes:
      - catalog_db_vol:/bin/db/
          # ports:
          #   - "2258:27017"
    
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - 8050:8000
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_vol:/data

  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - 9002:6379

  catalogApi:
    container_name: ps_catalogApi
    image: jinnybat/dotnet-microservice
    build:
       context: ..
       dockerfile: ./Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalogDb:27017
      - DatabaseSettings__DatabaseName=ProductDb
      - DatabaseSettings__CollectionName=Products
    depends_on:
      - catalogDb
  
  cartapi:
    container_name: ps_cartapi
    image: jinnybat/dotnet-microservice
    build:
       context: ..
       dockerfile: ./Services/Cart/Cart.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- DatabaseSettings__ConnectionString=mongodb://catalogDb:27017
      #- DatabaseSettings__DatabaseName=ProductDb
      #- DatabaseSettings__CollectionName=Products
    # depends_on:
    #   - redis

volumes:
  catalog_db_vol:
  portainer_vol:
    #external: true
